package com.example.orchestrator;

import com.example.orchestrator.llm.LlmClient;

import java.util.LinkedHashMap;
import java.util.Map;

/** LLM-backed actions for the reasoning-heavy SDLC stages. */
public final class LlmReasoningActions {
    private LlmReasoningActions() {}

    public static WorkflowNode.NodeAction requirements(LlmClient llm, String scenario) {
        return context -> {
            if (!llm.enabled()) {
                context.data().put("requirements", scenario);
                context.data().put("requirementsMode", "deterministic");
                return NodeResult.ok("requirements captured (deterministic fallback)");
            }

            String userRequirement = String.valueOf(
                    context.data().getOrDefault("userRequirement", defaultRequirement(scenario))
            );
            String system = """
                    You are a senior requirements analyst in an agentic SDLC system.
                    Analyze the requirement without inventing missing business facts.
                    Return concise JSON with keys: status, functionalRequirements,
                    nonFunctionalRequirements, ambiguities, clarificationQuestions,
                    acceptanceCriteria. status must be READY or NEEDS_INPUT.
                    """;
            String response = llm.complete(system, userRequirement);
            context.data().put("requirements", response);
            context.data().put("requirementsMode", "llm");
            return NodeResult.ok("requirements analyzed by LLM");
        };
    }

    public static WorkflowNode.NodeAction architecture(LlmClient llm) {
        return context -> {
            if (!llm.enabled()) {
                context.data().put("architecture", "Spring Boot layered architecture");
                return NodeResult.ok("architecture produced (deterministic fallback)");
            }

            String requirements = String.valueOf(context.data().get("requirements"));
            String system = """
                    You are a senior software architect. Based only on the supplied requirements,
                    propose a practical architecture. Return concise JSON with keys:
                    components, dataFlow, dataModel, security, scalability,
                    failureHandling, tradeoffs, openQuestions. Do not invent business requirements.
                    """;
            String response = llm.complete(system, requirements);
            context.data().put("architecture", response);
            return NodeResult.ok("architecture reasoned by LLM");
        };
    }

    public static WorkflowNode.NodeAction planning(LlmClient llm) {
        return context -> {
            if (!llm.enabled()) {
                context.data().put("plan", "implement service, tests, security and docs");
                return NodeResult.ok("tasks decomposed (deterministic fallback)");
            }

            Map<String, Object> planningContext = new LinkedHashMap<>();
            planningContext.put("requirements", context.data().get("requirements"));
            planningContext.put("architecture", context.data().get("architecture"));
            String system = """
                    You are a senior engineering planner. Break the supplied requirements and
                    architecture into small implementation tasks. Return concise JSON with keys:
                    tasks, dependencies, parallelizableTasks, validationSteps, risks.
                    Keep tasks implementation-oriented and testable.
                    """;
            String response = llm.complete(system, planningContext.toString());
            context.data().put("plan", response);
            return NodeResult.ok("implementation plan generated by LLM");
        };
    }

    private static String defaultRequirement(String scenario) {
        return switch (scenario.toLowerCase()) {
            case "brownfield" -> "Enhance the existing URL shortener with a safe maintenance capability while preserving backward compatibility.";
            case "ambiguous" -> "Make the URL shortener faster and more scalable.";
            default -> "Build a production-style URL shortener with create, redirect, expiration, authentication, rate limiting, analytics and observability.";
        };
    }
}
